name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/UPI_Mesh" ]; then
              cd /home/ubuntu
              git clone https://github.com/Shashank17singh/UPI_Mesh.git
            fi
            
            cd /home/ubuntu/UPI_Mesh
            git pull origin main
            sudo docker-compose up -d --build
